name: Build and Upload Firmware

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Clean PlatformIO cache
      run: |
        pio run --target clean
        rm -rf .pio/libdeps/
        
    - name: Build firmware
      run: |
        pio run
        
    - name: Extract version from source
      id: version
      run: |
        VERSION=$(grep -o '#define FIRMWARE_VERSION "[^"]*"' src/Config.h | cut -d'"' -f2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Firmware version: $VERSION"
        
    - name: Create build artifacts
      run: |
        mkdir -p build-output
        cp .pio/build/esp32doit-devkit-v1/firmware.bin build-output/
        
        # Create metadata
        cat > build-output/metadata.json << EOF
        {
          "version": "${{ steps.version.outputs.version }}",
          "buildDate": "$(date -u +%Y-%m-%d)",
          "buildTime": "$(date -u +%H:%M:%S)",
          "fileSize": $(stat -c%s .pio/build/esp32doit-devkit-v1/firmware.bin),
          "changelog": "Auto-built from GitHub commit ${{ github.sha }}",
          "commitHash": "${{ github.sha }}"
        }
        EOF
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ steps.version.outputs.version }}
        path: build-output/ 
